apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ncmk8rafy-python 
  janus-idp.io/tekton: ncmk8rafy-python
  backstage.io/kubernetes-id: ncmk8rafy-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ncmk8rafy-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  